import LegalPageShell from "@/components/landing/LegalPageShell";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — TaskyAI",
  description: "Terms of Service for TaskyAI.",
};

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2
      className="text-[20px] font-semibold text-[#f9f9f9] mb-3"
      style={{ letterSpacing: "-0.01em" }}
    >
      {children}
    </h2>
  );
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3
      className="text-[15px] font-semibold text-[#cecece] mb-2"
      style={{ letterSpacing: "0.2px" }}
    >
      {children}
    </h3>
  );
}

function Section({
  children,
  last = false,
}: {
  children: React.ReactNode;
  last?: boolean;
}) {
  return (
    <div
      className={`py-8 ${last ? "" : "border-b border-white/[0.06]"}`}
    >
      {children}
    </div>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p
      className="text-[14px] leading-[1.7] text-[#9c9c9d]"
      style={{ letterSpacing: "0.2px" }}
    >
      {children}
    </p>
  );
}

export default function TermsPage() {
  return (
    <LegalPageShell
      title="Terms of Service"
      subtitle="By using TaskyAI, you agree to the terms below."
      lastUpdated="January 15, 2025"
    >
      <Section>
        <SectionHeading>1. Acceptance of Terms</SectionHeading>
        <P>
          By accessing or using TaskyAI (&quot;the Service&quot;), you agree to be bound
          by these Terms of Service. If you do not agree to all of these terms,
          do not use the Service. These terms apply to all visitors, users, and
          others who access the Service.
        </P>
      </Section>

      <Section>
        <SectionHeading>2. Description of Service</SectionHeading>
        <P>
          TaskyAI is an AI-powered task planning tool that transforms unstructured
          briefs and text inputs into organized tasks with subtasks, priorities,
          and categories. The Service includes a chat interface, task management,
          and related features as described on our website.
        </P>
      </Section>

      <Section>
        <SectionHeading>3. User Accounts</SectionHeading>
        <SubHeading>3.1 Account Creation</SubHeading>
        <P>
          You may need to create an account to access certain features. You are
          responsible for maintaining the confidentiality of your account
          credentials and for all activities that occur under your account.
        </P>
        <SubHeading>3.2 Account Responsibilities</SubHeading>
        <P>
          You agree to provide accurate and complete information when creating
          your account and to update such information to keep it accurate. You
          must notify us immediately of any unauthorized use of your account.
        </P>
      </Section>

      <Section>
        <SectionHeading>4. Acceptable Use</SectionHeading>
        <P>
          You agree not to use the Service to: (a) violate any laws or
          regulations; (b) submit content that is unlawful, harmful, threatening,
          abusive, or defamatory; (c) attempt to gain unauthorized access to any
          portion of the Service; (d) use the Service to generate spam or
          automated messages; (e) reverse-engineer, decompile, or disassemble any
          part of the Service; or (f) use the Service in any manner that could
          damage, disable, or impair its operation.
        </P>
      </Section>

      <Section>
        <SectionHeading>5. Intellectual Property</SectionHeading>
        <SubHeading>5.1 Our Content</SubHeading>
        <P>
          The Service and its original content, features, and functionality are
          owned by TaskyAI and are protected by international copyright, trademark,
          and other intellectual property laws.
        </P>
        <SubHeading>5.2 Your Content</SubHeading>
        <P>
          You retain ownership of the briefs, text, and other content you submit
          to the Service. By submitting content, you grant TaskyAI a limited
          license to process that content solely to provide the Service to you.
        </P>
        <SubHeading>5.3 Generated Tasks</SubHeading>
        <P>
          Task output generated by the Service based on your inputs belongs to
          you. You may use, modify, and distribute generated task content as you
          see fit.
        </P>
      </Section>

      <Section>
        <SectionHeading>6. Subscriptions & Billing</SectionHeading>
        <SubHeading>6.1 Free Trial</SubHeading>
        <P>
          New users receive a 14-day free trial. No credit card is required to
          start a trial. At the end of the trial period, you may choose to
          subscribe to a paid plan or continue with limited free-tier access if
          available.
        </P>
        <SubHeading>6.2 Paid Plans</SubHeading>
        <P>
          Paid plans are billed in advance for the selected billing period
          (monthly, quarterly, or annually). Prices are subject to change with
          30 days&apos; notice. We will not change your price during an active billing
          cycle.
        </P>
        <SubHeading>6.3 Automatic Renewal</SubHeading>
        <P>
          Subscriptions auto-renew at the end of each billing period unless you
          cancel before the renewal date. You can cancel at any time from your
          account settings.
        </P>
      </Section>

      <Section>
        <SectionHeading>7. Limitation of Liability</SectionHeading>
        <P>
          TaskyAI is provided &quot;as is&quot; without warranties of any kind. We do not
          guarantee that the Service will be uninterrupted, error-free, or free
          of harmful components. In no event shall TaskyAI be liable for any
          indirect, incidental, special, or consequential damages arising from
          your use of the Service.
        </P>
      </Section>

      <Section>
        <SectionHeading>8. Termination</SectionHeading>
        <P>
          You may terminate your account at any time. We reserve the right to
          suspend or terminate your account if you breach these Terms. Upon
          termination, your right to use the Service will immediately cease.
          Sections relating to intellectual property, limitation of liability,
          and disclaimers will survive termination.
        </P>
      </Section>

      <Section>
        <SectionHeading>9. Modifications</SectionHeading>
        <P>
          We may update these Terms from time to time. We will notify you of
          material changes by posting the updated Terms on our website and
          updating the &quot;Last updated&quot; date. Your continued use of the Service
          after changes are posted constitutes acceptance of the revised Terms.
        </P>
      </Section>

      <Section>
        <SectionHeading>10. Governing Law</SectionHeading>
        <P>
          These Terms shall be governed by and construed in accordance with the
          laws of the jurisdiction in which TaskyAI is organized, without regard
          to its conflict of law provisions.
        </P>
      </Section>

      <Section>
        <SectionHeading>11. Contact</SectionHeading>
        <P>
          If you have questions about these Terms, please contact us at{" "}
          <a
            href="mailto:support@tasky.ai"
            className="text-[#FF6363] hover:underline underline-offset-2"
          >
            support@tasky.ai
          </a>
          .
        </P>
      </Section>
    </LegalPageShell>
  );
}